### ISSUE TITLE
Fields on "Social Settings" tab do not respond to LSB on admin side

### ISSUE THREAD

**Issue by MarcGuay** [qTranslate-Team/all-in-one-seo-pack-qtranslate-x#1] opened 2016-06-23 20:40 UTC
If you activate the "Social Meta" feature of AI1SEOP the fields it added to pages are not translatable.

Thanks for your efforts.
Marc

**Comment by johnclause** [comment] 2016-06-24 08:20
https://qtranslatexteam.wordpress.com/integration/ ?

**Comment by johnclause** [comment] 2016-06-24 08:21
Sorry, we are already in integration plugin ... ;)

**Comment by johnclause** [comment] 2016-06-24 08:21
Would you have time to integrate that part?

**Comment by MarcGuay** [comment] 2016-06-24 14:05
Unfortunately not at the moment.

**Comment by johnclause** [comment] 2016-06-24 17:54
Me neither ;) Could you describe the exact steps to reproduce the problem, so that it would be a well stated problem to solve, if someone finds time to work on it? It is easy for you, because you encounter it, but to reproduce it for somebody else, sometimes it takes hours to find out what exactly you meant.

**Comment by MarcGuay** [comment] 2016-06-24 18:00
1) In the WP admin, browse to All in One SEO->Feature Manager.
2) Activate the "Social Meta" feature.
3) Edit a post
4) In the All in One SEO Pack section, there is now a "Social Settings" tab, click it.
5) Add a title and description.
6) It is always the same for both languages.

**Comment by johnclause** [comment] 2016-06-24 18:06
I assume you tried [Raw ML format](https://qtranslatexteam.wordpress.com/multilingual-fields/), did you? What happened? Does it let you to keep Raw ML entry? Does front end show it translated correctly? Are you familiar with the concept of [integration](https://qtranslatexteam.wordpress.com/integration/)?

**Comment by MarcGuay** [comment] 2016-06-24 18:38
Raw ML format works (saved in backend and shown correctly on frontend).  I've never integrated a plugin with qTranslate-x.

**Comment by johnclause** [comment] 2016-06-24 20:03
Then we can close this issue? If raw ml works, then there is no problem. Having LSB at admin side is an easy thing to add if one wants it, but it is not necessary functionality-wise.

**Comment by MarcGuay** [comment] 2016-06-24 20:18
It depends on what your goals are with this plugin.  If they are to provide the minimum and leave it at that, then I would close the issue.  If you intend to continue improving the plugin, I would leave it open.

**Comment by johnclause** [comment] 2016-06-24 21:51
Yeah, good point. Honestly, I do not have plans, we are in crisis here. We just made a few plugins for ourselves and put them online for other people to enjoy, but other people immediately assumes that it is now our responsibility to support and to do work for them, and nobody pays donation. Did you, for example, pay anything? How people expect us to continue if there is no money coming in. All this support and development takes a lot of time. I have learned that people are very demanding and very unappreciative. Sad thing to realize ... Could you advise what to do to make people pay? Do we have to convert all those plugins into simple dummy paid products to sell in a usual way?
How much, for example, you would pay for this plugin with a happy feeling, without thinking that you might be overpaying? I am sorry for this off-topic deviation, I am not sure about the best way to proceed ...

You may put the following configuration into the field "Custom Configuration" on page `/wp-admin/options-general.php?page=qtranslate-x#integration`:

```
{"vendor":{"plugins/all-in-one-seo-pack":"1.0"},
"admin-config":{
"post":{
    "pages":{"post.php":"", "post-new.php":""},
    "forms":{
        "post":{
            "fields":{
                "aioseop_opengraph_settings_title_placeholder":{"jquery":"input[name='aioseop_opengraph_settings_title']", "attrs":["placeholder"], "encode":"display"},
                "aioseop_opengraph_settings_title":{"jquery":"input[name='aioseop_opengraph_settings_title']"},
                "aioseop_opengraph_settings_desc":{"jquery":"textarea[name='aioseop_opengraph_settings_desc']"}
            }
        }
    }
}
}
}
```

It should enable LSB on "Social Settings" tab, did it work for you? We will add that configuration to the next release, if you confirm it working well for you. Thank you.

**Comment by MarcGuay** [comment] 2016-06-27 14:07
Hi John,

That code works very well, thanks.  

Regarding the question of how to make a living off of open source software, unfortunately I don't have any suggestions for you.  I did not make a donation.  I'm familiar with the way that a lot of OS software users seem to feel like they're entitled to professional-level support and updates and also find it baffling.  I attribute it to either ignorance of how it works (you are volunteering your time), or an inability to behave as something other than a consumer of goods and services.

Take care,
Marc

**Comment by johnclause** [comment] 2016-06-27 15:12
Thanks for your feedback, Marc, yes, unfortunately, addressing that "inability" we have no choice, but to either abandon it all or to start selling licenses. As a user, what price for qtx per year would you personally consider reasonable? Without any research, just how much would you personally be willing to pay per year without a hard feeling?

I am closing this issue, we can still write into closed issue, or can reopen it if needed.

**Closed as completed by johnclause** 2016-06-27 15:12 UTC
Labels: enhancement

**Comment by MarcGuay** [comment] 2016-06-27 15:18
I personally do not have a budget for qTranslate, it was included as part of a project I was working on with a team, so it would really be a question for the project manager and company owner to decide.  However, if I were you, I would use commercial theme pricing as a comparison, or perhaps other Wordpress plugins like ACF Pro (https://www.advancedcustomfields.com/pro/) which have a paid option for extra features.

**Comment by johnclause** [comment] 2016-06-27 15:36
Thank you, Marc, yes, I have been doing this comparison research. Why don't you mention on next meeting with your team that qtx will soon require license. I would appreciate if you tell me how much they would care about it. My expectation is that it would not be important for them, as price would be very affordable for any company in any case, but I would really like to hear a specific number people would have in  mind as a reasonable price for such a product. Also, would they start paying or would they switch to other product then? Somebody in your company has made decision to use it in the past, how much that person would now be happy to pay? It would be helpful, if you could ask around that question within your surrounding. Thanks a lot.
